name:                just-enough-javascript
version:             0.1.0.0
github:              "githubuser/just-enough-javascript"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/just-enough-javascript#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies: 
    - text
    - megaparsec
    - parser-combinators
    - containers
    - vector
    - mtl
    - aeson
    - bytestring
    - array
    - language-javascript
    - process
    - scientific

executables:
  hjs:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - just-enough-javascript
      - haskeline
      - text
      - megaparsec
      - mtl
      - language-javascript
      - pretty-simple

tests:
  just-enough-javascript-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - just-enough-javascript
